In [87]:
# Import libraries and set desired options
import numpy as np
import pandas as pd
from scipy.sparse import hstack
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import TimeSeriesSplit, cross_val_score, GridSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [2]:
# A helper function for writing predictions to a file
def write_to_submission_file(predicted_labels, out_file,
                             target='target', index_label="session_id"):
    predicted_df = pd.DataFrame(predicted_labels,
                                index = np.arange(1, predicted_labels.shape[0] + 1),
                                columns=[target])
    predicted_df.to_csv(out_file, index_label=index_label)

In [3]:
sites = ['site%s' % i for i in range(1, 11)]
times = ['time%s' % i for i in range(1, 11)]

In [4]:
train_df = pd.read_csv('../../data/train_sessions.csv',
                       index_col='session_id', parse_dates=times)
test_df = pd.read_csv('../../data/test_sessions.csv',
                      index_col='session_id', parse_dates=times)

# Sort the data by time
train_df = train_df.sort_values(by='time1')

In [5]:
train_df[sites].fillna(0).astype('int').to_csv('train_sessions_text.txt', sep=' ', index=None, header=None)
test_df[sites].fillna(0).astype('int').to_csv('test_sessions_text.txt', sep=' ', index=None, header=None)

In [6]:
#####################################################

In [75]:
%%time
cv = TfidfVectorizer(ngram_range=(1, 3), max_features=50000, max_df=0.90, min_df=2)
with open('train_sessions_text.txt') as inp_train_file:
    X_train = cv.fit_transform(inp_train_file)
with open('test_sessions_text.txt') as inp_test_file:
    X_test = cv.transform(inp_test_file)
print(X_train.shape, X_test.shape)

(253561, 50000) (82797, 50000)
CPU times: user 10.8 s, sys: 298 ms, total: 11.1 s
Wall time: 10.5 s


In [76]:
# save train targets into a separate vector
y_train = train_df['target'].astype('int').values

In [77]:
# performing time series cross-validation
time_split = TimeSeriesSplit(n_splits=10)

In [78]:
# perform time series cross-validation with logistic regression
logit = LogisticRegression(C=1, random_state=17, solver='liblinear')

In [79]:
%%time
# hangs with n_jobs > 1, and locally this runs much faster
cv_scores = cross_val_score(logit, X_train, y_train, cv=time_split, scoring='roc_auc', n_jobs=-1) 

CPU times: user 823 ms, sys: 96.9 ms, total: 920 ms
Wall time: 4.05 s


In [80]:
cv_scores, cv_scores.mean(), cv_scores.std()

(array([0.81348435, 0.65520438, 0.87592305, 0.93549238, 0.84778787,
        0.88863608, 0.9248393 , 0.8747525 , 0.92845316, 0.92313193]),
 0.8667705000608688,
 0.07978822332630801)

In [81]:
#####################################################

In [82]:
logit.fit(X_train, y_train)

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=17, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [83]:
logit_test_pred = logit.predict_proba(X_test)[:, 1]
write_to_submission_file(logit_test_pred, 'subm1.csv') # 0.91288 -> 0.91382

### Features

In [84]:
features = {}

In [85]:
%time
# hour
def feature_hour(df):
    return df.fillna(0)['time1'].apply(lambda ts: ts.hour)

features['hour'] = {
    'train': feature_hour(train_df),
    'test': feature_hour(test_df),
}

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 5.96 µs


In [86]:
%time
# morning
def feature_morning(series):
    return ((series >= 7) & (series <= 11)).astype('int')

features['morning'] = {
    'train': feature_morning(features['hour']['train']),
    'test': feature_morning(features['hour']['test']),
}

# day
def feature_day(series):
    return ((series >= 12) & (series <= 18)).astype('int')

features['day'] = {
    'train': feature_day(features['hour']['train']),
    'test': feature_day(features['hour']['test']),
}

# evening
def feature_evening(series):
    return ((series >= 19) & (series <= 23)).astype('int')

features['evening'] = {
    'train': feature_evening(features['hour']['train']),
    'test': feature_evening(features['hour']['test']),
}

# night
def feature_night(series):
    return ((series >= 0) & (series <= 6)).astype('int')

features['night'] = {
    'train': feature_night(features['hour']['train']),
    'test': feature_night(features['hour']['test']),
}

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 7.87 µs


In [88]:
# duration
def feature_duration(df):
    df_times = df[times]
    return (df_times.max(axis=1) - df_times[times].min(axis=1)) / np.timedelta64(1, 's') / 1800

features['duration'] = {
    'train': feature_duration(train_df),
    'test': feature_duration(test_df),
}

In [89]:
# sites
def feature_sites(df):
    return df[sites].count(axis=1)

features['sites'] = {
    'train': feature_sites(train_df),
    'test': feature_sites(test_df),
}

In [90]:
# avg_time
def feature_avg_time(duration, sites):
    return duration / sites

features['avg_time'] = {
    'train': feature_avg_time(features['duration']['train'], features['sites']['train']),
    'test': feature_avg_time(features['duration']['test'], features['sites']['test']),
}

In [91]:
# first_time
def feature_first_time(df):
    return (df['time2'] - df['time1']).fillna(0) / np.timedelta64(1, 's')

features['first_time'] = {
    'train': feature_first_time(train_df),
    'test': feature_first_time(test_df),
}

In [92]:
# 2014
def feature_2014(df):
    return (df['time1'].apply(lambda ts: ts.year) == 2014).astype('int')

features['2014'] = {
    'train': feature_2014(train_df),
    'test': feature_2014(test_df),
}

In [93]:
def prepare_set(cols, is_test=False):
    return hstack([
        X_test if is_test else X_train, 
        *[features[col]['test' if is_test else 'train'].values.reshape(-1, 1) for col in cols]]
    )

In [94]:
columns = (
#         'hour', # 3.41
        'morning',  # 4.58
        'day',  # 4.61
        'evening',  # 0.15
        'night',  # -
#         'duration',  # 0.06
#         'sites',  # -
#         'avg_time',  # -
#         'first_time',  # 0
#         '2014',  # 0.1
    )

X_train_new = prepare_set(columns)
X_test_new = prepare_set(columns, True)

In [95]:
%%time
# performing time series cross-validation, we see an improvement in ROC AUC
# hangs with n_jobs > 1, and locally this runs much faster
cv_scores = cross_val_score(logit, X_train_new, y_train, cv=time_split, scoring='roc_auc', n_jobs=-1)

CPU times: user 977 ms, sys: 105 ms, total: 1.08 s
Wall time: 4.67 s


In [96]:
cv_scores, cv_scores.mean(), cv_scores.mean() - 0.8689298500287295
# (array([0.87008266, 0.80648914, 0.92857517, 0.96592745, 0.91598991,
        0.9516962 , 0.94826252, 0.93866035, 0.95200296, 0.95071618]),
#0.9228402542341649,
 0.05391040420543547)

(array([0.87008266, 0.80648914, 0.92857517, 0.96592745, 0.91598991,
        0.9516962 , 0.94826252, 0.93866035, 0.95200296, 0.95071618]),
 0.9228402542341649,
 0.05391040420543547)

In [97]:
#####################################################

In [98]:
logit.fit(X_train_new, y_train)

logit_test_pred2 = logit.predict_proba(X_test_new)[:, 1]
write_to_submission_file(logit_test_pred2, 'subm2.csv') # 0.93843

In [99]:
# tune regularization parameter C
c_values = np.logspace(-2, 2, 10)

logit_grid_searcher = GridSearchCV(
    estimator=logit, param_grid={'C': c_values}, scoring='roc_auc', n_jobs=1, cv=time_split, verbose=1
)

In [100]:
%%time
logit_grid_searcher.fit(X_train_new, y_train) # WTF? Locally, it's 3min 30s

Fitting 10 folds for each of 10 candidates, totalling 100 fits


[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:  2.0min finished


CPU times: user 6min 41s, sys: 1min 8s, total: 7min 50s
Wall time: 2min


GridSearchCV(cv=TimeSeriesSplit(max_train_size=None, n_splits=10),
       error_score='raise',
       estimator=LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=17, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': array([1.00000e-02, 2.78256e-02, 7.74264e-02, 2.15443e-01, 5.99484e-01,
       1.66810e+00, 4.64159e+00, 1.29155e+01, 3.59381e+01, 1.00000e+02])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='roc_auc', verbose=1)

In [101]:
logit_grid_searcher.best_score_, logit_grid_searcher.best_params_  # (0.9249450807614793, {'C': 1.6681005372000592})

(0.9249450807614793, {'C': 1.6681005372000592})

In [102]:
logit_test_pred3 = logit_grid_searcher.predict_proba(X_test_new)[:, 1]
write_to_submission_file(logit_test_pred3, 'subm3.csv')

In [103]:
%%time
# performing time series cross-validation, we see an improvement in ROC AUC
cv_scores = cross_val_score(logit_grid_searcher.best_estimator_, X_train_new, y_train, cv=time_split, scoring='roc_auc', n_jobs=-1)

CPU times: user 1.09 s, sys: 97.3 ms, total: 1.19 s
Wall time: 6.42 s


In [106]:
cv_scores, cv_scores.mean(), cv_scores.std() # 0.9249450807614791

(array([0.88342964, 0.80461656, 0.93157956, 0.9669782 , 0.91693854,
        0.95127441, 0.95164868, 0.93786943, 0.95342815, 0.95168763]),
 0.9249450807614791,
 0.04601868425363776)

In [105]:
logit_test_pred3 = logit_grid_searcher.predict_proba(X_test_new)[:, 1]
write_to_submission_file(logit_test_pred3, 'subm5.csv') # 0.94637