In [163]:
# Import libraries and set desired options
import numpy as np
import pandas as pd
from scipy.sparse import hstack
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import TimeSeriesSplit, cross_val_score, GridSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from matplotlib import pyplot as plt

In [2]:
# A helper function for writing predictions to a file
def write_to_submission_file(predicted_labels, out_file,
                             target='target', index_label="session_id"):
    predicted_df = pd.DataFrame(predicted_labels,
                                index = np.arange(1, predicted_labels.shape[0] + 1),
                                columns=[target])
    predicted_df.to_csv(out_file, index_label=index_label)

In [3]:
sites = ['site%s' % i for i in range(1, 11)]
times = ['time%s' % i for i in range(1, 11)]

In [4]:
train_df = pd.read_csv('../../data/train_sessions.csv',
                       index_col='session_id', parse_dates=times)
test_df = pd.read_csv('../../data/test_sessions.csv',
                      index_col='session_id', parse_dates=times)

# Sort the data by time
train_df = train_df.sort_values(by='time1')

In [5]:
train_df[sites].fillna(0).astype('int').to_csv('train_sessions_text.txt', sep=' ', index=None, header=None)
test_df[sites].fillna(0).astype('int').to_csv('test_sessions_text.txt', sep=' ', index=None, header=None)

In [6]:
#####################################################

In [75]:
%%time
cv = TfidfVectorizer(ngram_range=(1, 3), max_features=50000, max_df=0.90, min_df=2)
with open('train_sessions_text.txt') as inp_train_file:
    X_train = cv.fit_transform(inp_train_file)
with open('test_sessions_text.txt') as inp_test_file:
    X_test = cv.transform(inp_test_file)
print(X_train.shape, X_test.shape)

(253561, 50000) (82797, 50000)
CPU times: user 10.8 s, sys: 298 ms, total: 11.1 s
Wall time: 10.5 s


In [76]:
# save train targets into a separate vector
y_train = train_df['target'].astype('int').values

In [77]:
# performing time series cross-validation
time_split = TimeSeriesSplit(n_splits=10)

In [421]:
# perform time series cross-validation with logistic regression
logit = LogisticRegression(C=1, random_state=17, solver='liblinear')

In [79]:
%%time
# hangs with n_jobs > 1, and locally this runs much faster
cv_scores = cross_val_score(logit, X_train, y_train, cv=time_split, scoring='roc_auc', n_jobs=-1) 

CPU times: user 823 ms, sys: 96.9 ms, total: 920 ms
Wall time: 4.05 s


In [80]:
cv_scores, cv_scores.mean(), cv_scores.std()

(array([0.81348435, 0.65520438, 0.87592305, 0.93549238, 0.84778787,
        0.88863608, 0.9248393 , 0.8747525 , 0.92845316, 0.92313193]),
 0.8667705000608688,
 0.07978822332630801)

In [81]:
#####################################################

In [82]:
logit.fit(X_train, y_train)

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=17, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [83]:
logit_test_pred = logit.predict_proba(X_test)[:, 1]
write_to_submission_file(logit_test_pred, 'subm1.csv') # 0.91288 -> 0.91382

### Features

In [84]:
features = {}

In [390]:
# %time
# # start_hour
# def feature_start_hour(df):
#     return df.fillna(0)['time1'].apply(lambda ts: ts.hour)

# features['start_hour'] = {
#     'train': feature_start_hour(train_df),
#     'test': feature_start_hour(test_df),
# }

features['start_hour_scale'] = {
    'train': features['start_hour']['train'] / 23,
    'test': features['start_hour']['test'] / 23,
}

In [170]:
%time
# morning
def feature_morning(series):
    return ((series >= 7) & (series <= 11)).astype('int')

features['morning'] = {
    'train': feature_morning(features['start_hour']['train']),
    'test': feature_morning(features['start_hour']['test']),
}

# day
def feature_day(series):
    return ((series >= 12) & (series <= 18)).astype('int')

features['day'] = {
    'train': feature_day(features['start_hour']['train']),
    'test': feature_day(features['start_hour']['test']),
}

# evening
def feature_evening(series):
    return ((series >= 19) & (series <= 23)).astype('int')

features['evening'] = {
    'train': feature_evening(features['start_hour']['train']),
    'test': feature_evening(features['start_hour']['test']),
}

# night
def feature_night(series):
    return ((series >= 0) & (series <= 6)).astype('int')

features['night'] = {
    'train': feature_night(features['start_hour']['train']),
    'test': feature_night(features['start_hour']['test']),
}

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 6.2 µs


In [171]:
# duration
def feature_duration(df):
    df_times = df[times]
    return (df_times.max(axis=1) - df_times[times].min(axis=1)) / np.timedelta64(1, 's') / (1800)

features['duration'] = {
    'train': feature_duration(train_df),
    'test': feature_duration(test_df),
}

In [89]:
# # sites
# def feature_sites(df):
#     return df[sites].count(axis=1)

# features['sites'] = {
#     'train': feature_sites(train_df),
#     'test': feature_sites(test_df),
# }

In [493]:
# avg_time
def feature_avg_time(df):
    return df[times].apply(lambda x: x.apply(lambda v: int(v.timestamp()) if not pd.isnull(v) else v)).diff(axis=1).median(axis=1, skipna=True)

features['avg_time'] = {
    'train': feature_avg_time(train_df).fillna(0),
    'test': feature_avg_time(test_df).fillna(0),
}


/Users/m.yuldashev/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py:3250: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)


In [91]:
# # first_time
# def feature_first_time(df):
#     return (df['time2'] - df['time1']).fillna(0) / np.timedelta64(1, 's')

# features['first_time'] = {
#     'train': feature_first_time(train_df),
#     'test': feature_first_time(test_df),
# }

In [92]:
# 2014
def feature_2014(df):
    return (df['time1'].apply(lambda ts: ts.year) == 2014).astype('int')

features['2014'] = {
    'train': feature_2014(train_df),
    'test': feature_2014(test_df),
}

In [173]:
%time
# end_hour
def feature_end_hour(df):
    return df[times].max(axis=1).apply(lambda ts: ts.hour)

features['end_hour'] = {
    'train': feature_end_hour(train_df),
    'test': feature_end_hour(test_df),
}

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 6.2 µs


In [183]:
features['hours_start'] = {
    'train': pd.get_dummies(features['start_hour']['train']),
    'test': pd.get_dummies(features['start_hour']['test']),
}

features['hours_end'] = {
    'train': pd.get_dummies(features['end_hour']['train']),
    'test': pd.get_dummies(features['end_hour']['test']),
}

In [322]:
%time
# day_of_week
def feature_day_of_week(df):
    return df['time1'].apply(lambda t: t.weekday())

features['day_of_week'] = {
    'train': feature_day_of_week(train_df) / 7,
    'test': feature_day_of_week(test_df) / 7,
}

CPU times: user 2 µs, sys: 9 µs, total: 11 µs
Wall time: 15.3 µs


In [324]:
%time
# month
def feature_month(df):
    return df['time1'].apply(lambda t: t.month)

features['month'] = {
    'train': feature_month(train_df) / 12,
    'test': feature_month(test_df) / 12,
}

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.96 µs


In [367]:
# return
def feature_return(df):
    return df[sites].count(axis=1) - df[sites].nunique(axis=1)

%time
features['return'] = {
    'train': feature_return(train_df),
    'test': feature_return(test_df),
}

features['return'] = {
    'train': features['return']['train'] / features['return']['train'].max(),
    'test': features['return']['test'] / features['return']['test'].max(),
}

In [184]:
def prepare_set(cols, is_test=False):
    return hstack([
        X_test if is_test else X_train, 
        *[features[col]['test' if is_test else 'train'].values.reshape(-1, 1) for col in cols]]
    )

In [503]:
columns = (
        'start_hour', # 3.41
#         'end_hour',
        'morning',  # 4.58
        'day',  # 4.61
        'evening',  # 0.15
#         'night',  # -
        'duration',  # 0.06
#         'sites',  # -
        'avg_time',  # -
#         'first_time',  # 0
        '2014',  # 0.1
        'day_of_week',
#         'month',
        'return',
    )

X_train_new = hstack([
    prepare_set(columns),
    features['hours_start']['train'],
    features['hours_end']['train'],
])
X_test_new = hstack([
    prepare_set(columns, True),
    features['hours_start']['test'],
    features['hours_end']['test'],
])

# X_train_new = np.hstack([
#     *[features[col]['train'].values.reshape(-1, 1) for col in columns],
#     features['hours_start']['train'],
#     features['hours_end']['train'],
# ])

In [504]:
%%time
# performing time series cross-validation, we see an improvement in ROC AUC
# hangs with n_jobs > 1, and locally this runs much faster
cv_scores = cross_val_score(logit, X_train_new, y_train, cv=time_split, scoring='roc_auc', n_jobs=-1)

CPU times: user 1.78 s, sys: 234 ms, total: 2.01 s
Wall time: 16.6 s


In [505]:
cv_scores, cv_scores.mean(), cv_scores.std()
# (array([0.87008266, 0.80648914, 0.92857517, 0.96592745, 0.91598991,
#        0.9516962 , 0.94826252, 0.93866035, 0.95200296, 0.95071618]),
# 0.9228402542341649,
# 0.05391040420543547)

(array([0.66856492, 0.84394834, 0.9667966 , 0.95611567, 0.92841135,
        0.97998039, 0.86541741, 0.96169892, 0.96827599, 0.98123315]),
 0.9120442750292028,
 0.0929146439131644)

In [506]:
#####################################################

In [507]:
logit.fit(X_train_new, y_train)

logit_test_pred2 = logit.predict_proba(X_test_new)[:, 1]
write_to_submission_file(logit_test_pred2, 'subm2.csv') # 0.93843

In [508]:
# tune regularization parameter C
c_values = np.logspace(-2, 2, 10)

logit_grid_searcher = GridSearchCV(
    estimator=logit, param_grid={'C': c_values, 'penalty': ['l1,l2']}, scoring='roc_auc', n_jobs=-1, cv=time_split, verbose=1
)

In [509]:
%%time
logit_grid_searcher.fit(X_train_new, y_train) # WTF? Locally, it's 3min 30s

Fitting 10 folds for each of 10 candidates, totalling 100 fits


[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:  6.2min finished


CPU times: user 21min 37s, sys: 3min 30s, total: 25min 7s
Wall time: 6min 24s


GridSearchCV(cv=TimeSeriesSplit(max_train_size=None, n_splits=10),
       error_score='raise',
       estimator=LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=17, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': array([1.00000e-02, 2.78256e-02, 7.74264e-02, 2.15443e-01, 5.99484e-01,
       1.66810e+00, 4.64159e+00, 1.29155e+01, 3.59381e+01, 1.00000e+02])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='roc_auc', verbose=1)

In [510]:
logit_grid_searcher.best_score_, logit_grid_searcher.best_params_  # (0.9249450807614793, {'C': 1.6681005372000592})

(0.9179783659248585, {'C': 12.915496650148826})

In [511]:
logit_test_pred3 = logit_grid_searcher.predict_proba(X_test_new)[:, 1]
write_to_submission_file(logit_test_pred3, 'subm3.csv')

In [512]:
%%time
# performing time series cross-validation, we see an improvement in ROC AUC
cv_scores = cross_val_score(logit_grid_searcher.best_estimator_, X_train_new, y_train, cv=time_split, scoring='roc_auc', n_jobs=-1)

CPU times: user 1.53 s, sys: 125 ms, total: 1.65 s
Wall time: 34.6 s


In [513]:
cv_scores, cv_scores.mean(), cv_scores.std() # 0.9249450807614791, 0.04601868425363776

(array([0.66754064, 0.83568729, 0.9723427 , 0.961643  , 0.93652106,
        0.97490628, 0.91897183, 0.95863116, 0.97520044, 0.97833926]),
 0.9179783659248585,
 0.0930102230227458)

In [514]:
logit_test_pred3 = logit_grid_searcher.predict_proba(X_test_new)[:, 1]
write_to_submission_file(logit_test_pred3, 'submission.csv') # 0.94637

In [197]:
logit_grid_searcher.best_estimator_.coef_[0][50000:]

array([-3.81480034, -0.01736845, -3.30004216,  0.        , -0.18582495,
       -1.77447782,  0.67294971, -2.09300448, -0.4344428 ,  0.16381344,
        0.04503104, -2.18394556, -0.88249761,  0.99764465,  0.8805937 ,
        0.96199189, -0.68742948, -0.58969348, -0.76390284, -0.72722688,
       -0.53178948, -0.18582495, -1.77447782,  0.67294971, -2.09300448,
       -0.4344428 ,  0.16381344,  0.04503104, -2.18394556, -0.88249761,
        0.99764465,  0.8805937 ,  0.96199189, -0.68742948, -0.58969348,
       -0.76390284, -0.72722688, -0.53178948])